CREATE USER adm WITH ENCRYPTED PASSWORD 'admin';
CREATE USER viw WITH ENCRYPTED PASSWORD 'viewer';

CREATE DATABASE sre;

GRANT CONNECT ON DATABASE sre TO adm, viw;

GRANT USAGE ON SCHEMA public TO adm, viw;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO viw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO viw;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO adm;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO adm;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;