server {
    listen 80;
    server_name example.com;
    server_tokens off;
    more_clear_headers Server;
    root /var/www/html; # Document root where your PHP files are located

    index index.php index.html index.htm;
    autoindex off; # Disable directory listing
    


    location / {
        try_files $uri $uri/ =404; # Tries serving static files first
    }

    location ^~ /.git/ { 
        deny all; 
        return 404; 
    }

    # Also block ".git" without trailing slash (/.git)
    location = /.git {
        deny all;
        return 404;
    }

    # Pass PHP scripts to PHP-FPM
    location ~ \.php$ {
        include fastcgi_params; # Includes default FastCGI parameters

        # Use a Unix socket (common on Linux systems) or TCP address (e.g., 127.0.0.1:9000)
        fastcgi_pass 127.0.0.1:9000;

        fastcgi_index index.php;
        # Specifies the script filename parameter passed to PHP-FPM
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Optional: Deny access to .htaccess files if present (Apache specific, but good practice)
    location ~ /\.ht {
        deny all;
    }
}
